### ISSUE TITLE
Создать все необходимые миграции и модели к ним

### ISSUE THREAD

**Issue by sintsov** [SGolenzovskiy/altrc#1]
Согласно, образцу в [коммите 1] (https://github.com/SGolenzovskiy/altrc/commit/2cfa6bead32ac79fcaaf1879d9c4a8186efe6b3a), [коммите 2](https://github.com/SGolenzovskiy/altrc/commit/fbed22d60cb6c603a73e6d06b5b5f9234a9e8853),  [коммите 3](https://github.com/SGolenzovskiy/altrc/commit/8a43c8220269bad24f098cab87b4d7b230d51ce2)
нужно создать миграции для таблиц `country_projects`, `tag_projects`, `references_projects`
почему название таблиц именно такие должны быть смотри [тут](https://laravel.ru/docs/v5/eloquent) 
![image](https://cloud.githubusercontent.com/assets/7813708/16855506/4cdd9752-4a1e-11e6-8d84-8dbdcd9a947b.png)

почитать про миграции можно [тут](https://laravel.ru/docs/v5/migrations) 
пример создания миграции: 

`php artisan make:migration create_service_projects_table --create="service_projects"`

После того как ты создашь миграции и добавишь нужные поля.
Нужно создать модели под них:

`php artisan make:model ServiceProject`

про то как правильно именуются модели и таблицы, можно посмотреть [тут](http://stackoverflow.com/questions/14449912/convention-table-names-with-underscore) 

Аналогичные модели для примера у тебя есть.

**Comment by SGolenzovskiy** [comment]
f2e71e9e4e4d129ec3b79cd8618e5c59d3720475
