### ISSUE TITLE
Кнопку для вызова окна, куда перетаскиваются рефы - сделать ее нягляднее и подписать

### ISSUE THREAD

**Issue by skyeone** [SGolenzovskiy/altrc#10]

**Comment by sintsov** [comment]
Стасончик, мой мега интерфейс был забракован) надо будет продумать иной вариант

**Comment by skyeone** [comment]
Я бы предложил подвинуть ее левее (на уровень меню, но с его правой стороны), оставить с красной подложкой и просто подписать "Отобранные" 

+

Добавить туда внутрь окна кнопку а ля "копировать в буфер"

**Comment by SGolenzovskiy** [comment]
Доработано согласно предложениям.
