### ISSUE TITLE
Добавить кнопку "Сбросить фильтр" для обнуления текущей фильтрации

### ISSUE THREAD

**Issue by skyeone** [SGolenzovskiy/altrc#11]

**Comment by skyeone** [comment]
И пусть отображает текущую фильтрацию в строчке где-то под фильтрами (исследование рынка + машиностроение + Россия)  иначе очень быстро путаешься, если забываешь с чего-то снять выделение

**Comment by SGolenzovskiy** [comment]
Кнопка добавлена.
