### ISSUE TITLE
Улучшить способ присвоения свойств фильтра проекту в карточке проекта

### ISSUE THREAD

**Issue by skyeone** [SGolenzovskiy/altrc#12]
Если мы правильно понимаем, то сейчас нужно через ctrl+click выбрать в карточке проекта "отрасль", "географию" и прочее, чтобы выбранное закрепилось за проектом для последующего поиска по фильтрам, так?

Было бы здорово, если бы он где-то сразу выводил текущие активные свойства проекта и была возможность их сбросить 1м кликом.

**Comment by SGolenzovskiy** [comment]
Доработка выполнена.
