### ISSUE TITLE
Загрузить все логотипы

### ISSUE THREAD

**Issue by skyeone** [SGolenzovskiy/altrc#13]

**Comment by SGolenzovskiy** [comment]
Для загрузки логотипов необходим обновленный csv-файл с заполненным столбцом Логотип.
Пример заполнения:
1. Для "_AEA Technology_" значение в столбце Логотип: _Agroevrosoyz-Sareks**.png**_
2. Для "_Медицина-Альфа Страхование_" значение в столбце _Логотип: Alpha**.jpg**_

**Comment by SGolenzovskiy** [comment]
Логотипы загружены.
