### ISSUE TITLE
Заполнить все таблицы тестовыми данными

### ISSUE THREAD

**Issue by sintsov** [SGolenzovskiy/altrc#2]
Нужно будет создать миграции (seeds) которые заполнят базу тестовыми данными
На эту тему оф [дока](https://laravel.com/docs/5.1/seeding)
На русском есть [тут](https://laravel.ru/docs/v5/migrations) раздел "Загрузка начальных данных в БД"

**Comment by SGolenzovskiy** [comment]
**FYI:**
1. Обновление автозагрузки
`composer dump-autoload`
2. Инсталляция данных
`php artisan db:seed`
3. Переустановка данных с предварительной очисткой таблиц
` php artisan migrate:refresh --seed`
7f7526709b6c0a2500d4b809aff941d456e1552f
