### ISSUE TITLE
Загрузка проектов

### ISSUE THREAD

**Issue by sintsov** [SGolenzovskiy/altrc#8]
Требуется реализовать парсер из csv и загрузку данных в базу.

**Comment by sintsov** [comment]
Тестовая таблица
[CSV - Таблица (1).xlsx](https://github.com/SGolenzovskiy/altrc/files/407565/CSV.-.1.xlsx)

**Comment by sintsov** [comment]
из файла видно, что у нас все же возможна ситуация когда нет референций, надо ее предусмотреть, я постараюсь это учесть.

**Comment by sintsov** [comment]
удалил пока все значения с ? и сохранил как csv
[projects.csv.zip](https://github.com/SGolenzovskiy/altrc/files/407579/projects.csv.zip)

**Comment by sintsov** [comment]
случайно нашлепал коммент в другом тиките :)
https://github.com/SGolenzovskiy/altrc/issues/9

**Comment by skyeone** [comment]
Обратите внимание, что при заливке проектов, само описание проекта также является его 1м вариантом формулировки. Просто сейчас выходит, что нигде референций нет, а описание проекта - это и есть первая референция

**Comment by SGolenzovskiy** [comment]
> а описание проекта - это и есть первая референция
Насколько я понимаю, под описанием проекта имелся ввиду столбец "Проект" в csv-файле, а не поле "Описание", которое содержит описание проекта (Сорский молибденовый комбинат, входит в состав компания SMR (Союзметаллрусурс) холдинга "Базовый элемент").

Сейчас в референцию записывается значение из поля "Проект".
