### ISSUE TITLE
Добавить поле "Компания" в карточку проекта

### ISSUE THREAD

**Issue by skyeone** [SGolenzovskiy/altrc#9]

**Comment by sintsov** [comment]
Стас, судя по всему тут просто название проекта надо переименовать в компанию

**Comment by sintsov** [comment]
Наврал, проект поле есть такое, а вот компания все таки новое поле!!!
В базу я его добавлю сам, так как он мне нужен для загрузки данных, твоя задача его вывести на форму и сохранять его значение

**Comment by sintsov** [comment]
Поле называется: company
![image](https://cloud.githubusercontent.com/assets/7813708/17494260/9e5c69b2-5dbc-11e6-83ed-e3e2f6f63aec.png)

**Comment by sintsov** [comment]
Стас, в таблице, есть случай типа Ландия у которого название проекта
Бизнес-план проекта "Организация производства гофротары на промплощадке ОАО "КСК"  г. Серпухов Московской обл."

после попытки такое загрузить все ломается, так как используются кавычки как экранирующие символы. Поэтому чтобы избежать такой проблемы при загрузки данных, надо при сохранение документа использовать в качестве экранирующего символа: ~ 

Думаю тильда точно не встретиться в тексте :)

**Comment by sintsov** [comment]
Обновленный файл с тильдой в качестве экранирующего символа
[projects.csv.zip](https://github.com/SGolenzovskiy/altrc/files/407684/projects.csv.zip)

**Comment by sintsov** [comment]
Почему то в случае когда мой либреофис встречает похоже кавычки он заколбашивает перенос строки, поэтому нужно править такие места в ручную. 
![image](https://cloud.githubusercontent.com/assets/7813708/17495538/19159138-5dc2-11e6-8379-c49ee08aa654.png)
Если видишь такое сообщение offset значит он не может индекс в массиве соответствующий получить, значит надо руками эту строчку подправить. Добавляешь var_dump
![image](https://cloud.githubusercontent.com/assets/7813708/17495594/5f8d515a-5dc2-11e6-8b26-befa179b88ea.png)
и смотришь в какой строке проблема
![image](https://cloud.githubusercontent.com/assets/7813708/17495621/7f805a52-5dc2-11e6-9a03-5e95ce436a2a.png)

очищеный архив для теста можно взять у меня в папке 
`database/seeds/csv/projects.csv`

**Comment by sintsov** [comment]
Загузчик работает коммит https://github.com/SGolenzovskiy/altrc/commit/3d4beb2a3556707202049be43b694777abb2ec8e

Как только тебе пришлют актуализированный список, надо будет его прогрузить
```
php artisan migrate:refresh
php artisan db:seed
```

**Comment by skyeone** [comment]
Здесь имеется в виду именно новое поле, при чем его важно отображать, когда выводится таблица по фильтрам, потому что по лого и названию проекта сложно искать, по компаниям проще

**Comment by SGolenzovskiy** [comment]
Поле компания добавлено:

1. В таблицу на главной странице
2. В карточку редактирования проекта
3. В карточку добавления проекта
